<?php
/**
 * Created by PhpStorm.
 * User: Quan Lee
 * Date: 12/7/16
 * Time: 11:10 AM
 */
$title = 'Company List';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('company', array('action'=>'add'));?>">Add new company</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Country</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($companys as $company) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($company->name);?></td>
            <td><?php echo $this->escapeHtml($company->address);?></td>
            <td><?php echo $this->escapeHtml($company->country);?></td>
            <td> <a href="<?php echo $this->url('company', array('action'=>'edit', 'id' => $company->id));?>">Sửa</a> |
                <a href="<?php echo $this->url('company', array('action'=>'delete', 'id' => $company->id));?>">Xóa</a>
            </td>
        </tr>
    <?php endforeach;
    ?>
</table>